jobs:
  - job: Testing
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '11.9.0'
        displayName: 'Install Node.js'

      - task: DockerCompose@0
        displayName: 'Start Redis in docker-compose'
        inputs:
          action: 'Run a specific service'
          serviceName: redis

      - script: yarn install
        displayName: 'Install dependencies'

      - script: 'yarn test'
        displayName: 'Run unit tests'

      - task: kasunkodagoda.slack-notification.slack-notification-task.SlackNotification@5
        displayName: 'Post Slack Notification Success'
        inputs:
          SlackApiToken: 'xoxp-160914285315-471337868992-495682478979-c4c99061d2251d149a9e084f68e7305e'
          IconUrl: 'https://2.bp.blogspot.com/-8Rp9gpF_22Q/Wgm4qRmwjNI/AAAAAAAAP3o/fowNNrMUrrwsRMIjZ_JkheuNB-f2qFifACLcBGAs/s200/Microsoft.VisualStudio.Services.Icons.Default.png'
          Channel: '#ci-cd'
          Color: good
          Message: 'AzureDevops Build Pipeline `$(Build.BuildId)`'
          AuthorName: '$(Build.RequestedFor)'
          Title: '$(Build.Repository.Name)'
          FooterText: '$(Build.SourceBranchName)'
          Text: 'Tests successfull'
        condition: in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues')

      - task: kasunkodagoda.slack-notification.slack-notification-task.SlackNotification@5
        displayName: 'Post Slack Notification Failure'
        inputs:
          SlackApiToken: 'xoxp-160914285315-471337868992-495682478979-c4c99061d2251d149a9e084f68e7305e'
          IconUrl: 'https://2.bp.blogspot.com/-8Rp9gpF_22Q/Wgm4qRmwjNI/AAAAAAAAP3o/fowNNrMUrrwsRMIjZ_JkheuNB-f2qFifACLcBGAs/s200/Microsoft.VisualStudio.Services.Icons.Default.png'
          Channel: '#ci-cd'
          Color: danger
          Message: 'AzureDevops Build Pipeline `$(Build.BuildId)`'
          AuthorName: '$(Build.RequestedFor)'
          Title: '$(Build.Repository.Name)'
          FooterText: '$(Build.SourceBranchName)'
          Text: 'Tests failed'
        condition: not(in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues'))

  - job: 'Build_Master'
    dependsOn: Testing
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    steps:
      - task: Docker@1
        displayName: 'Build an image'
        inputs:
          azureSubscriptionEndpoint: Shakhr
          azureContainerRegistry: 'devyossregistry.azurecr.io'
          imageName: 'yosswebsocket:$(Build.BuildId)'

      - task: Docker@1
        displayName: 'Push an image'
        inputs:
          azureSubscriptionEndpoint: Shakhr
          azureContainerRegistry: 'devyossregistry.azurecr.io'
          command: 'Push an image'
          imageName: 'yosswebsocket:$(Build.BuildId)'
          includeSourceTags: true

      - task: kasunkodagoda.slack-notification.slack-notification-task.SlackNotification@5
        displayName: 'Post Slack Notification Success'
        inputs:
          SlackApiToken: 'xoxp-160914285315-471337868992-495682478979-c4c99061d2251d149a9e084f68e7305e'
          IconUrl: 'https://2.bp.blogspot.com/-8Rp9gpF_22Q/Wgm4qRmwjNI/AAAAAAAAP3o/fowNNrMUrrwsRMIjZ_JkheuNB-f2qFifACLcBGAs/s200/Microsoft.VisualStudio.Services.Icons.Default.png'
          Channel: '#ci-cd'
          Color: good
          Message: 'AzureDevops Build Pipeline `$(Build.BuildId)`'
          AuthorName: '$(Build.RequestedFor)'
          Title: '$(Build.Repository.Name)'
          FooterText: '$(Build.SourceBranchName)'
          Text: 'Build and push to registry successfull [PRD]'
        condition: in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues')

      - task: kasunkodagoda.slack-notification.slack-notification-task.SlackNotification@5
        displayName: 'Post Slack Notification Failure'
        inputs:
          SlackApiToken: 'xoxp-160914285315-471337868992-495682478979-c4c99061d2251d149a9e084f68e7305e'
          IconUrl: 'https://2.bp.blogspot.com/-8Rp9gpF_22Q/Wgm4qRmwjNI/AAAAAAAAP3o/fowNNrMUrrwsRMIjZ_JkheuNB-f2qFifACLcBGAs/s200/Microsoft.VisualStudio.Services.Icons.Default.png'
          Channel: '#ci-cd'
          Color: danger
          Message: 'AzureDevops Build Pipeline `$(Build.BuildId)`'
          AuthorName: '$(Build.RequestedFor)'
          Title: '$(Build.Repository.Name)'
          FooterText: '$(Build.SourceBranchName)'
          Text: 'Build or push failed [PRD]'
        condition: not(in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues'))

  - job: 'Build_Dev'
    dependsOn: Testing
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/dev-release'))
    steps:
      - task: Docker@0
        displayName: 'Build an image'
        inputs:
          azureSubscriptionEndpoint: Shakhr
          azureContainerRegistry: '{"loginServer":"devyossregistry.azurecr.io", "id" : "/subscriptions/9e84de30-cdfb-4069-be06-e29f2f343102/resourceGroups/RG-EUR-FR-DEV-YOSS/providers/Microsoft.ContainerRegistry/registries/devyossregistry"}'
          imageName: 'yosswebsocket:$(Build.BuildId)'

      - task: Docker@0
        displayName: 'Push an image'
        inputs:
          azureSubscriptionEndpoint: Shakhr
          azureContainerRegistry: '{"loginServer":"devyossregistry.azurecr.io", "id" : "/subscriptions/9e84de30-cdfb-4069-be06-e29f2f343102/resourceGroups/RG-EUR-FR-DEV-YOSS/providers/Microsoft.ContainerRegistry/registries/devyossregistry"}'
          command: 'Push an image'
          imageName: 'yosswebsocket:$(Build.BuildId)'
          includeSourceTags: true

      - task: kasunkodagoda.slack-notification.slack-notification-task.SlackNotification@5
        displayName: 'Post Slack Notification Success'
        inputs:
          SlackApiToken: 'xoxp-160914285315-471337868992-495682478979-c4c99061d2251d149a9e084f68e7305e'
          IconUrl: 'https://2.bp.blogspot.com/-8Rp9gpF_22Q/Wgm4qRmwjNI/AAAAAAAAP3o/fowNNrMUrrwsRMIjZ_JkheuNB-f2qFifACLcBGAs/s200/Microsoft.VisualStudio.Services.Icons.Default.png'
          Channel: '#ci-cd'
          Color: good
          Message: 'AzureDevops Build Pipeline `$(Build.BuildId)`'
          AuthorName: '$(Build.RequestedFor)'
          Title: '$(Build.Repository.Name)'
          FooterText: '$(Build.SourceBranchName)'
          Text: 'Build and push to registry successfull [DEV]'
        condition: in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues')

      - task: kasunkodagoda.slack-notification.slack-notification-task.SlackNotification@5
        displayName: 'Post Slack Notification Failure'
        inputs:
          SlackApiToken: 'xoxp-160914285315-471337868992-495682478979-c4c99061d2251d149a9e084f68e7305e'
          IconUrl: 'https://2.bp.blogspot.com/-8Rp9gpF_22Q/Wgm4qRmwjNI/AAAAAAAAP3o/fowNNrMUrrwsRMIjZ_JkheuNB-f2qFifACLcBGAs/s200/Microsoft.VisualStudio.Services.Icons.Default.png'
          Channel: '#ci-cd'
          Color: danger
          Message: 'AzureDevops Build Pipeline `$(Build.BuildId)`'
          AuthorName: '$(Build.RequestedFor)'
          Title: '$(Build.Repository.Name)'
          FooterText: '$(Build.SourceBranchName)'
          Text: 'Build or push failed [DEV]'
        condition: not(in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues'))
