version: '3.7'
services:
  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${REGISTRY-yoss}/yoss-websocket:${VERSION-alpha}
    ports:
      - '8080:80'
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development

  redis:
    image: redis
    command: redis-server
    ports:
      - '6378:6379'
