version: '3.7'
services:
  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${REGISTRY-yoss}/yoss-websocket:${VERSION-alpha}
    ports:
      - '${PORT}:80'
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_SECRET=${REDIS_SECRET}
      - NODE_ENV=development

  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_SECRET}
    ports:
      - '6378:6379'
